version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      backstage:
        patterns:
          - '@backstage/*'
      types:
        patterns:
          - '@types/*'
    ignore:
      # We use backstage-cli for these updates
      - dependency-name: "@backstage/*"
      - dependency-name: "@humanitec/*"